// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package engine

import (
	"encoding/json"

	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/core/types"
)

var _ = (*executionChunkMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (e ExecutionChunk) MarshalJSON() ([]byte, error) {
	type ExecutionChunk struct {
		ChunkHeader  types.ChunkHeader   `json:"chunkHeader"`
		Transactions []hexutil.Bytes     `json:"transactions"`
		Withdrawals  []*types.Withdrawal `json:"withdrawals"`
	}
	var enc ExecutionChunk
	enc.ChunkHeader = e.ChunkHeader
	if e.Transactions != nil {
		enc.Transactions = make([]hexutil.Bytes, len(e.Transactions))
		for k, v := range e.Transactions {
			enc.Transactions[k] = v
		}
	}
	enc.Withdrawals = e.Withdrawals
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (e *ExecutionChunk) UnmarshalJSON(input []byte) error {
	type ExecutionChunk struct {
		ChunkHeader  *types.ChunkHeader  `json:"chunkHeader"`
		Transactions []hexutil.Bytes     `json:"transactions"`
		Withdrawals  []*types.Withdrawal `json:"withdrawals"`
	}
	var dec ExecutionChunk
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.ChunkHeader != nil {
		e.ChunkHeader = *dec.ChunkHeader
	}
	if dec.Transactions != nil {
		e.Transactions = make([][]byte, len(dec.Transactions))
		for k, v := range dec.Transactions {
			e.Transactions[k] = v
		}
	}
	if dec.Withdrawals != nil {
		e.Withdrawals = dec.Withdrawals
	}
	return nil
}
